### PR TITLE
Add caching

### PR DESCRIPTION
**Pull request by DrChainsaw**
This is the proposed fix for #172 

Unfortunately, only caching of the solution seems to have a pretty disappointing impact on the benchmark:

```julia
julia> function bench(optimizer, N = 30_000)
           model = Model(with_optimizer(optimizer))
           @variable(model, x[i = 1:N] >= i)
           @objective(model, Min, sum(x))
           optimize!(model)
           @benchmark value.($x)
        end
bench (generic function with 2 methods)

julia> bench(Cbc.Optimizer)
Optimal - objective value 4.50015e+08
Optimal objective 450015000 - 0 iterations time 0.002
BenchmarkTools.Trial: 2 samples with 1 evaluation.
 Range (min … max):  3.524 s …    4.264 s  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     3.894 s               ┊ GC (median):    0.00%        
 Time  (mean ± σ):   3.894 s ± 523.174 ms  ┊ GC (mean ± σ):  0.00% ± 0.00%

  █                                                        █  
  █▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁█ ▁
  3.52 s         Histogram: frequency by time         4.26 s <
```

Profiling shows that `Cbc_isProvenOptimal` and `Cbc_getNumIntegers` seems to dominate the computation time.

After adding caching of those two performance appears to be back on track:

```julia
julia> bench(Cbc.Optimizer)
Optimal - objective value 4.50015e+08
Optimal objective 450015000 - 0 iterations time 0.002
BenchmarkTools.Trial: 205 samples with 1 evaluation.
 Range (min … max):  19.858 ms … 34.276 ms  ┊ GC (min … max): 0.00% … 13.42%
 Time  (median):     23.973 ms              ┊ GC (median):    0.00%
 Time  (mean ± σ):   24.479 ms ±  2.629 ms  ┊ GC (mean ± σ):  1.76% ±  4.52%

  ▄   █                               ▄  █                    ▁
  █▁▁▁█▁▁▁▁▁▁▁▁▆▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▆▁▁▁█▁▁█▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁ █
  20.4 ms         Histogram: frequency by time        23.4 ms <

 Memory estimate: 6.18 MiB, allocs estimate: 330002.
```

There are probably alot of other `Cbc_X` functions which are also too slow, but I lack the overall understanding to pinpoint them.

I have tried to make a minimum of changes for easier reviewing of the "core changes", but please suggest better structure and names if you think this is the way to go. I don't mind nitpicking.

### CODE REVIEW

**Comment by odow** [comment]
The fact that it's all the `Cbc_` functions makes me think there is a bigger issue going on...

**Comment by DrChainsaw** [comment]
> The fact that it's all the Cbc_ functions makes me think there is a bigger issue going on...

I agree!

**Comment by odow** [comment]
What's the benchmark with your latest changes?

**Comment by odow** [comment]
Just a note to say that I haven't forgotten about this PR. But I've been busy with the MOI 0.10 release so I haven't had a chance to take a deeper look yet.

**Comment by DrChainsaw** [comment]
No problem at all! 

I'm not blocked by this, just trying to do my duty as a user and report issues (and fix what I feel is within reach for me to fix). Let me know if there is anything more I can do (the "deeper issue" feels a bit out of reach for me atm).

**Pull request closed without merging**
