### PR TITLE
Add support for MOI.NumberOfThreads

### LINKED ISSUE #220: Support MOI.NumberOfThreads

### PR DESCRIPTION
**Pull request by hannes-uppman**
Closes #220

### CODE REVIEW

**Comment by odow** [comment]
I avoided adding this previously because of https://github.com/jump-dev/Cbc.jl/issues/186

https://github.com/jump-dev/Cbc.jl/blob/f495d977a3189283ec0c74741a3da0dadbb3ddb9/src/MOI_wrapper/MOI_wrapper.jl#L136-L142

But I guess it doesn't hurt.

**Comment by hannes-uppman** [comment]
I see.
Would it be better to have `MOI.supports(::Optimizer, ::MOI.NumberOfThreads)` return `false` on Windows?
Not having support on e.g. Linux because of a problem on Windows seems bad.

**Comment by odow** [comment]
I think this is fine to say "yes" and then throw a warning. I'm taking a look at the segfault issue. It used to be very sporadic. But it seems regular now.

**Comment by hannes-uppman** [comment]
Ok! Thanks!

**Pull request merged**
